### ISSUE TITLE
Unposed displacement for T-pose (not A-pose)

### ISSUE THREAD

**Issue by FishWoWater** [zycliao/TailorNet_dataset#18]
Thanks for your excellent work! 

I couldn't find the unposed displacement for each garment type in T-pose. I have found unposed disp for A-pose or other simulated poses under directory `style_shape` or `pose`. 

Is the displacement available for T-pose? (if not, perhaps I can unpose A-pose disp to T-pose)

By the way, how did you unpose the displacements? It seems that directly inverse the LBS process will introduce some possible artifacts.

**Comment by zycliao** [comment]
Hey, the displacement in the dataset is all for T-pose. 
You can look at https://github.com/zycliao/TailorNet_dataset/blob/66f26cb0577f322a207846ce6cce68faee46b888/smpl_torch.py#L175
It adds displacement on the T-pose mesh (v_deformed)

The unpose code is in https://github.com/zycliao/TailorNet_dataset/blob/66f26cb0577f322a207846ce6cce68faee46b888/smpl_torch.py#L218
Basically, it finds the inverse of LBS. And as of now, we don't find artifacts.

**Comment by FishWoWater** [comment]
@zycliao thanks for your reply 

yes, I understand that the displacement is added on the T-pose and then we perform LBS to warp the body / cloth to specific poses. But here I am finding the displacement exactly registered for T-pose: the cloth template draped on a T-pose body. Did I miss or misunderstand something? 

Besides, [This CVPR 2021 work](https://openaccess.thecvf.com/content/CVPR2021/papers/Santesteban_Self-Supervised_Collision_Handling_via_Generative_3D_Garment_Models_for_Virtual_CVPR_2021_paper.pdf) pointed out the artifacts of such inverse LBS, in its figure3, it that reasonable?

**Comment by zycliao** [comment]
Hi, sorry for the late reply. I think your understanding is correct. Regarding the artifacts in Fig3b, it's totally OK because we only care about the deformation after LBS. However, I guess the network can learn it better if the displacement is more continuous as in Fig3d, but that's out of the scope of TailorNet.

**Comment by zycliao** [comment]
I see. So you're looking for the shirt draped on T-pose. Unfortunately in our dataset, the canonical shirt is all draped on A-pose. And we didn't simulate it in T-pose.

Is it possible that you input A-pose to the simulation engine as the start frame and gradually transition it to T-pose?

If that's impossible, I don't think using inverse-LBS of cloth mesh in A-pose is a good idea as it will bring the wrinkle in A-pose to T-pose and change the shape of the cloth. However, since in our dataset, there're some poses very close to T-pose, you may try using inverse-LBS on those poses to reduce artifacts as much as possible.

Another workaround is to use the TailorNet [model ](https://github.com/chaitanya100100/TailorNet)and input theta=0 (T-pose) to the model.

**Comment by FishWoWater** [comment]
@zycliao 
Yes, I think it's feasible to input A-pose as the start frame and try simulation engine, I will try that~

Thanks =)

**Comment by FishWoWater** [comment]
@zycliao 

Hi! Is the uv unwarping of each garment available? (coords in the UV Space)

**Comment by chaitanya100100** [comment]
Since UVMap is not part of TailorNet, we don't provide it. However, you can generate it using blender. Here are a couple of references:

https://www.youtube.com/watch?v=illIxYKb-1k&ab_channel=RoyalSkies

https://all3dp.com/2/blender-uv-mapping-simply-explained/

**Comment by FishWoWater** [comment]
@chaitanya100100 Thanks, it works
